version: '3.8'

services:
  service-landings:
    build: .
    ports:
      - "8001:8000"
    environment:
      - DEBUG=True
    volumes:
      - .:/app
    networks:
      - landings-network

networks:
  landings-network:
    driver: bridge
