version: '3.8'

services:
  microservice_enid:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${SERVICENAME}_service
    container_name: ${SERVICENAME}_service
    ports:
      - "8088:8080"
    env_file:
      - .env
    environment:
      - DEBUG=True
      - DJANGO_RUNNING_MIGRATIONS=True
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - backend
      - enid_service_network

  postgres:
    container_name: service-landings-postgres
    image: postgres:alpine
    ports:
      - "5445:5432"
    environment:
      - POSTGRES_DB=landings_db
      - POSTGRES_USER=landings_user
      - POSTGRES_PASSWORD=landings_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U landings_user -d landings_db"]
      interval: 10s
      retries: 5

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
  enid_service_network:
    driver: bridge