# Generated by Django 4.2.7 on 2025-08-30 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la plantilla', max_length=100)),
                ('slug', models.SlugField(help_text='Slug único de la plantilla', unique=True)),
                ('template_type', models.CharField(choices=[('hero', 'Hero Section'), ('product', 'Product Showcase'), ('testimonial', 'Testimonials'), ('features', 'Features'), ('pricing', 'Pricing'), ('cta', 'Call to Action')], help_text='Tipo de plantilla', max_length=50)),
                ('config', models.JSONField(default=dict, help_text='Configuración de la plantilla')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la plantilla está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Landing',
                'verbose_name_plural': 'Plantillas de Landing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(help_text='ID del producto en el servicio enid-store')),
                ('landing_type', models.CharField(choices=[('default', 'Landing por Defecto'), ('promotional', 'Landing Promocional'), ('seasonal', 'Landing Estacional'), ('category', 'Landing por Categoría'), ('custom', 'Landing Personalizada')], default='custom', help_text='Tipo de landing para este producto', max_length=50)),
                ('is_primary', models.BooleanField(default=False, help_text='Indica si es la landing principal del producto')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la relación está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(help_text='Plantilla de landing asociada al producto', on_delete=django.db.models.deletion.CASCADE, related_name='product_landings', to='landing.landingtemplate')),
            ],
            options={
                'verbose_name': 'Relación Producto-Plantilla',
                'verbose_name_plural': 'Relaciones Producto-Plantilla',
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['product_id'], name='landing_pro_product_8703b9_idx'), models.Index(fields=['template'], name='landing_pro_templat_5c71be_idx'), models.Index(fields=['is_primary'], name='landing_pro_is_prim_31ec36_idx'), models.Index(fields=['is_active'], name='landing_pro_is_acti_822e03_idx'), models.Index(fields=['landing_type'], name='landing_pro_landing_cae592_idx')],
                'unique_together': {('product_id', 'template')},
            },
        ),
    ]
