# Generated by Django 4.2.7 on 2025-08-29 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
    ]
