# Generated by Django 4.2.7 on 2025-08-29 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20250829_1605'),
    ]

    operations = [
    ]
